### ISSUE TITLE
datafile64.bin

### ISSUE THREAD

**Issue by Demon1019** [ashllay/BnsDatTool#1]
Hi.
Is there any possibility that you can add function to repack datafile64.bin in this tool? There is old version (cmd-based) of dat-tool to repacking x32-bit dat+datafile inside. Can you (since this tool can work with x64 dat) add this functionality?

Or maybe you can point me in the direction of already existing solution to this?

**Comment by Demon1019** [comment]
Thanks. Translated program to my lang. Dumping working like a charm. Gonna try translating and merging xml`s later. If something will go wrong, Ill post. Best regards.

**Comment by lvatrung** [comment]
pls, teach me repack datafile64.bin 👍
