### ISSUE TITLE
Could you complete the "Translation"

### ISSUE THREAD

**Issue by Darkfullen** [ashllay/BnsDatTool#2]
I've downloaded the tools, but i found that there was no function when i click the "merge" button. Thus i could not trans my translation.xml to 32bit or 64bit .bin files.
I saw the source codes, and i found the program was not complete.
Could you please complete it? Thankyou so much.

我下载了bnsdattool，但是当我点击“merge”按钮时，我发现没有任何响应和动作。所以我无法将translation.xml翻译到32位或64位的.bin文件里面去。
我看了一下源代码，发现translation部分的代码仅写了读取文件的部分，转换的部分没有完成，
能麻烦完成一下这部分代码吗？非常感谢。

**Comment by ashllay** [comment]
working on it again maybe a test version will be ready tomorrow.

**Comment by Darkfullen** [comment]
Thx. I'll wait it.
Best wishes.

**Comment by ashllay** [comment]
finished you can check here http://www.bladeandsouldojo.com/forums/topic/184834-dat-files-packerunpacker/

**Comment by Darkfullen** [comment]
Thanks for your update.
  But now I do not understand what can the "Merge" button do.
  I tried  to select my "translation.xml" on the "Merge File" option, and clicked the "Merge" button. After that I checked the "translation.xml', the first line " < ?xml version="1.0" encoding="utf-8"? > " was lost and I can open the "translation.xml" without "UTF-8 no-bom" mode. And the file size has increased about 3MB.
  Hope it can support CMD command, ummmm... just like ronny1982's bnsdat, but not locked the .bin files' name. Thus ".bat" can be used.
  64bin files translation test OK!

**Comment by ashllay** [comment]
I will be making a small guide how to use this tool.
if you use this tool to extract translation.xml form bin file it will generate in "utf-8".

**Comment by Darkfullen** [comment]
I tried.
It will help me merge a old translation.xml to a new translation.xml.
That's great.
But if it can not lost the first line.....

Btw, when I conpleted the translation, a message
"7IF A==B that mean have something wrong! Check source code and fix it." 
will be appeared. What's it?

**Comment by Darkfullen** [comment]
Maybe it's the best BNS bat tools.
Never feel so good.
Thanks for your devolopment!

**Comment by ashllay** [comment]
This ""7IF A==B that mean have something wrong! Check source code and fix it."" mean its all fine .

updated you can find it on bnsdojo same mediafire link.

i will be closing this and and you can contact me on discord (Ashllay | Myiumi#8131) or bnsdojo.
