### ISSUE TITLE
issues with last commit

### ISSUE THREAD

**Issue by Demon1019** [ashllay/BnsDatTool#3]
When compiling

lib\Translation\TranslateFileDal.cs(31,76,31,85): error CS0117: "Resources" dont have assigned "translate".
lib\Translation\TranslateFileBl.cs(84,59,84,83): error CS0117: "Resources" dont have assigned "AutoIdSearchNotSupported".

Maybe bcos Im using VisualStudio Preview instead of release, bcos on adding project I got different (older then my) .NET prompt? Can it be bcos diff .NET?

**Comment by ashllay** [comment]
I'm using Visual studio 2015 .net framework 4.5.2.

**Comment by Demon1019** [comment]
Installed VisualStudio Community release. .NET prompt not appearing now, but same things popping on compiling. Idk my fault it is or not.
